apiVersion: v1
kind: Service
metadata:
  name: pig-service
  namespace: a-sergeev
spec:
  type: NodePort
  selector:
    app: pig
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30004
